language: java
jdk:
  - openjdk8

sudo: required
services:
  - docker

script: mvn package dockerfile:build

before_deploy: 
  - 'mvn versions:set -DnewVersion=$TRAVIS_TAG'
  - 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin'
deploy:
  provider: script
  script: mvn package dockerfile:push -DskipTests=true -Ddockerfile.tag=$TRAVIS_TAG
  on:
    repo: jossemarGT/cms-galatea
    branch: master
    tags: true
