language: java
jdk:
  - openjdk8

sudo: required
services:
  - docker

script: mvn clean package dockerfile:build

before_deploy: 
  - mvn versions:set -DnewVersion=$TRAVIS_TAG
  - docker --version
deploy:
  provider: script
  script: mvn package dockerfile:build dockerfile:push -DskipTests=true -Ddockerfile.username=$DOCKER_USERNAME -Ddockerfile.password=$DOCKER_PASSWORD
  on:
    repo: jossemarGT/cms-galatea
    branch: master
    tags: true
