// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jossemargt.cmsgalatea.model.dod;

import com.jossemargt.cmsgalatea.model.Attachment;
import com.jossemargt.cmsgalatea.model.dod.AttachmentFactory;

privileged aspect AttachmentFactory_Roo_JpaEntityFactory {
    
    /**
     * Creates a new {@link Attachment} with the given index.
     * 
     * @param index position of the Attachment
     * @return a new transient Attachment
     */
    public Attachment AttachmentFactory.create(int index) {
        Attachment obj = new Attachment();
        return obj;
    }
    
}
