// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jossemargt.cmsgalatea.model.dod;

import com.jossemargt.cmsgalatea.model.Contest;
import com.jossemargt.cmsgalatea.model.dod.ContestFactory;

privileged aspect ContestFactory_Roo_JpaEntityFactory {
    
    /**
     * Creates a new {@link Contest} with the given index.
     * 
     * @param index position of the Contest
     * @return a new transient Contest
     */
    public Contest ContestFactory.create(int index) {
        Contest obj = new Contest();
        return obj;
    }
    
}
