// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jossemargt.cmsgalatea.model.dod;

import com.jossemargt.cmsgalatea.model.dod.ContestDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ContestDataOnDemand_Roo_Configurable {
    
    declare @type: ContestDataOnDemand: @Configurable;
    
}
