// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jossemargt.cmsgalatea.model.dod;

import com.jossemargt.cmsgalatea.model.Dataset;
import com.jossemargt.cmsgalatea.model.dod.DatasetFactory;

privileged aspect DatasetFactory_Roo_JpaEntityFactory {
    
    /**
     * Creates a new {@link Dataset} with the given index.
     * 
     * @param index position of the Dataset
     * @return a new transient Dataset
     */
    public Dataset DatasetFactory.create(int index) {
        Dataset obj = new Dataset();
        return obj;
    }
    
}
