// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jossemargt.cmsgalatea.model.dod;

import com.jossemargt.cmsgalatea.model.Statement;
import com.jossemargt.cmsgalatea.model.dod.StatementFactory;

privileged aspect StatementFactory_Roo_JpaEntityFactory {
    
    /**
     * Creates a new {@link Statement} with the given index.
     * 
     * @param index position of the Statement
     * @return a new transient Statement
     */
    public Statement StatementFactory.create(int index) {
        Statement obj = new Statement();
        return obj;
    }
    
}
