// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jossemargt.cmsgalatea.model.dod;

import com.jossemargt.cmsgalatea.model.Task;
import com.jossemargt.cmsgalatea.model.dod.TaskFactory;

privileged aspect TaskFactory_Roo_JpaEntityFactory {
    
    /**
     * Creates a new {@link Task} with the given index.
     * 
     * @param index position of the Task
     * @return a new transient Task
     */
    public Task TaskFactory.create(int index) {
        Task obj = new Task();
        return obj;
    }
    
}
