// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jossemargt.cmsgalatea.repository;

import static org.assertj.core.api.Assertions.assertThat;

import com.jossemargt.cmsgalatea.model.Task;
import com.jossemargt.cmsgalatea.model.dod.TaskDataOnDemand;
import com.jossemargt.cmsgalatea.repository.TaskRepository;
import com.jossemargt.cmsgalatea.repository.TaskRepositoryIT;
import io.springlets.data.domain.GlobalSearch;
import java.util.List;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;

privileged aspect TaskRepositoryIT_Roo_RepositoryJpaIntegrationTest {
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @Rule
    public ExpectedException TaskRepositoryIT.thrown = ExpectedException.none();
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @Autowired
    private TaskRepository TaskRepositoryIT.repository;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @Autowired
    private TaskDataOnDemand TaskRepositoryIT.dod;
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return TaskRepository
     */
    public TaskRepository TaskRepositoryIT.getRepository() {
        return repository;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return TaskDataOnDemand
     */
    public TaskDataOnDemand TaskRepositoryIT.getDod() {
        return dod;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Before
    public void TaskRepositoryIT.checkDataOnDemandHasInitializedCorrectly() {
        assertThat(getDod().getRandomTask())
            .as("Check data on demand for 'Task' initializes correctly by getting a random Task")
            .isNotNull();
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    public void TaskRepositoryIT.countShouldReturnExpectedValue() {
        // Verify
        assertThat(getRepository().count()).as("Check there are available 'Task' entries").isGreaterThan(0);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    public void TaskRepositoryIT.findOneShouldReturnExistingTask() {
        // Setup
        Long id = getRandomTaskId();
        
        // Exercise
        Task task = getRepository().findOne(id);
        
        // Verify
        assertThat(task).as("Check that findOne illegally returned null for id %s", id).isNotNull();
        assertThat(id).as("Check the identifier of the found 'Task' is the same used to look for it")
            .isEqualTo(task.getId());
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    public void TaskRepositoryIT.findAllShouldReturnAllTasks() {
        // Setup
        assertThat(getRepository().count())
            .as("Check the number of entries is not too big (250 entries). "
                + "If it is, please review the tests so it doesn't take too long to run them")
            .isLessThan(250);
        
        // Exercise
        List<Task> result = getRepository().findAll();
        
        // Verify
        assertThat(result).as("Check 'findAll' returns a not null list of entries").isNotNull();
        assertThat(result.size()).as("Check 'findAll' returns a not empty list of entries")
            .isGreaterThan(0);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    public void TaskRepositoryIT.findAllCustomNotFilteredNotPagedShouldReturnAllTasks() {
        // Exercise
        Page<Task> all = getRepository().findAll((GlobalSearch) null, new PageRequest(0, getDod().getSize()));
        
        // Verify
        assertThat(all.getNumberOfElements())
            .as("Check 'findAll' with null 'GlobalSearch' and no pagination returns all entries")
            .isEqualTo(getDod().getSize());
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     */
    @Test
    public void TaskRepositoryIT.findAllCustomNotFilteredPagedShouldReturnATasksPage() {
        // Exercise
        Page<Task> all = getRepository().findAll((GlobalSearch) null, new PageRequest(0, 3));
        
        // Verify
        assertThat(all.getNumberOfElements())
            .as("Check result number is not greater than the page size").isLessThanOrEqualTo(3);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return Long
     */
    private Long TaskRepositoryIT.getRandomTaskId() {
        Task task = getDod().getRandomTask();
        Long id = task.getId();
        assertThat(id).as("Check the Data on demand generated a 'Task' with an identifier").isNotNull();
        return id;
    }
    
}
