// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jossemargt.cmsgalatea.model;

import com.jossemargt.cmsgalatea.model.ContestTest;
import com.jossemargt.cmsgalatea.model.dod.ContestFactory;
import com.jossemargt.cmsgalatea.model.dod.TaskFactory;

privileged aspect ContestTest_Roo_JpaUnitTest {
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private ContestFactory ContestTest.contestFactory = new ContestFactory();
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private TaskFactory ContestTest.taskFactory = new TaskFactory();
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return ContestFactory
     */
    public ContestFactory ContestTest.getContestFactory() {
        return contestFactory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param contestFactory
     */
    public void ContestTest.setContestFactory(ContestFactory contestFactory) {
        this.contestFactory = contestFactory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return TaskFactory
     */
    public TaskFactory ContestTest.getTaskFactory() {
        return taskFactory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param taskFactory
     */
    public void ContestTest.setTaskFactory(TaskFactory taskFactory) {
        this.taskFactory = taskFactory;
    }
    
}
