// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jossemargt.cmsgalatea.model;

import com.jossemargt.cmsgalatea.model.TaskTest;
import com.jossemargt.cmsgalatea.model.dod.AttachmentFactory;
import com.jossemargt.cmsgalatea.model.dod.DatasetFactory;
import com.jossemargt.cmsgalatea.model.dod.StatementFactory;
import com.jossemargt.cmsgalatea.model.dod.SubmissionFormatElementFactory;
import com.jossemargt.cmsgalatea.model.dod.TaskFactory;

privileged aspect TaskTest_Roo_JpaUnitTest {
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private AttachmentFactory TaskTest.attachmentFactory = new AttachmentFactory();
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private DatasetFactory TaskTest.datasetFactory = new DatasetFactory();
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private StatementFactory TaskTest.statementFactory = new StatementFactory();
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private SubmissionFormatElementFactory TaskTest.submissionFormatElementFactory = new SubmissionFormatElementFactory();
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private TaskFactory TaskTest.taskFactory = new TaskFactory();
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return AttachmentFactory
     */
    public AttachmentFactory TaskTest.getAttachmentFactory() {
        return attachmentFactory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param attachmentFactory
     */
    public void TaskTest.setAttachmentFactory(AttachmentFactory attachmentFactory) {
        this.attachmentFactory = attachmentFactory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return DatasetFactory
     */
    public DatasetFactory TaskTest.getDatasetFactory() {
        return datasetFactory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param datasetFactory
     */
    public void TaskTest.setDatasetFactory(DatasetFactory datasetFactory) {
        this.datasetFactory = datasetFactory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return StatementFactory
     */
    public StatementFactory TaskTest.getStatementFactory() {
        return statementFactory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param statementFactory
     */
    public void TaskTest.setStatementFactory(StatementFactory statementFactory) {
        this.statementFactory = statementFactory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return SubmissionFormatElementFactory
     */
    public SubmissionFormatElementFactory TaskTest.getSubmissionFormatElementFactory() {
        return submissionFormatElementFactory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param submissionFormatElementFactory
     */
    public void TaskTest.setSubmissionFormatElementFactory(SubmissionFormatElementFactory submissionFormatElementFactory) {
        this.submissionFormatElementFactory = submissionFormatElementFactory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return TaskFactory
     */
    public TaskFactory TaskTest.getTaskFactory() {
        return taskFactory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param taskFactory
     */
    public void TaskTest.setTaskFactory(TaskFactory taskFactory) {
        this.taskFactory = taskFactory;
    }
    
}
