// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jossemargt.cmsgalatea.web;

import com.jossemargt.cmsgalatea.model.dod.ContestFactory;
import com.jossemargt.cmsgalatea.service.api.ContestService;
import com.jossemargt.cmsgalatea.web.ContestsCollectionJsonController;
import com.jossemargt.cmsgalatea.web.ContestsCollectionJsonControllerIT;
import io.springlets.boot.test.autoconfigure.web.servlet.SpringletsWebMvcTest;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.test.web.servlet.MockMvc;

privileged aspect ContestsCollectionJsonControllerIT_Roo_JsonControllerIntegrationTest {
    
    declare @type: ContestsCollectionJsonControllerIT: @RunWith(SpringRunner.class);
    
    declare @type: ContestsCollectionJsonControllerIT: @SpringletsWebMvcTest(controllers = ContestsCollectionJsonController.class, secure = false);
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @Autowired
    private MockMvc ContestsCollectionJsonControllerIT.mvc;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @MockBean
    private ContestService ContestsCollectionJsonControllerIT.contestService;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private ContestFactory ContestsCollectionJsonControllerIT.factory = new ContestFactory();
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return MockMvc
     */
    public MockMvc ContestsCollectionJsonControllerIT.getMvc() {
        return mvc;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return ContestService
     */
    public ContestService ContestsCollectionJsonControllerIT.getContestService() {
        return contestService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param contestService
     */
    public void ContestsCollectionJsonControllerIT.setContestService(ContestService contestService) {
        this.contestService = contestService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return ContestFactory
     */
    public ContestFactory ContestsCollectionJsonControllerIT.getFactory() {
        return factory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param factory
     */
    public void ContestsCollectionJsonControllerIT.setFactory(ContestFactory factory) {
        this.factory = factory;
    }
    
    /**
     * Test method example. To be implemented by developer.
     * 
     */
    @Test
    public void ContestsCollectionJsonControllerIT.testMethodExample() {
        // Setup
        // Previous tasks
        
        // Exercise
        // Execute method to test
        
        // Verify
        // Check results with assertions
    }
    
}
