// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jossemargt.cmsgalatea.web;

import com.jossemargt.cmsgalatea.model.dod.ContestFactory;
import com.jossemargt.cmsgalatea.service.api.ContestService;
import com.jossemargt.cmsgalatea.web.ContestsItemJsonControllerIT;
import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.test.web.servlet.MockMvc;

privileged aspect ContestsItemJsonControllerIT_Roo_JsonControllerIntegrationTest {
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @Autowired
    private MockMvc ContestsItemJsonControllerIT.mvc;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @MockBean
    private ContestService ContestsItemJsonControllerIT.contestService;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private ContestFactory ContestsItemJsonControllerIT.factory = new ContestFactory();
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return MockMvc
     */
    public MockMvc ContestsItemJsonControllerIT.getMvc() {
        return mvc;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return ContestService
     */
    public ContestService ContestsItemJsonControllerIT.getContestService() {
        return contestService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param contestService
     */
    public void ContestsItemJsonControllerIT.setContestService(ContestService contestService) {
        this.contestService = contestService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return ContestFactory
     */
    public ContestFactory ContestsItemJsonControllerIT.getFactory() {
        return factory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param factory
     */
    public void ContestsItemJsonControllerIT.setFactory(ContestFactory factory) {
        this.factory = factory;
    }
    
    /**
     * Test method example. To be implemented by developer.
     * 
     */
    @Test
    public void ContestsItemJsonControllerIT.testMethodExample() {
        // Setup
        // Previous tasks
        
        // Exercise
        // Execute method to test
        
        // Verify
        // Check results with assertions
    }
    
}
