// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jossemargt.cmsgalatea.web;

import com.jossemargt.cmsgalatea.model.dod.TaskFactory;
import com.jossemargt.cmsgalatea.service.api.TaskService;
import com.jossemargt.cmsgalatea.web.TasksItemJsonControllerIT;
import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.test.web.servlet.MockMvc;

privileged aspect TasksItemJsonControllerIT_Roo_JsonControllerIntegrationTest {
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @Autowired
    private MockMvc TasksItemJsonControllerIT.mvc;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @MockBean
    private TaskService TasksItemJsonControllerIT.taskService;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private TaskFactory TasksItemJsonControllerIT.factory = new TaskFactory();
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return MockMvc
     */
    public MockMvc TasksItemJsonControllerIT.getMvc() {
        return mvc;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return TaskService
     */
    public TaskService TasksItemJsonControllerIT.getTaskService() {
        return taskService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param taskService
     */
    public void TasksItemJsonControllerIT.setTaskService(TaskService taskService) {
        this.taskService = taskService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return TaskFactory
     */
    public TaskFactory TasksItemJsonControllerIT.getFactory() {
        return factory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param factory
     */
    public void TasksItemJsonControllerIT.setFactory(TaskFactory factory) {
        this.factory = factory;
    }
    
    /**
     * Test method example. To be implemented by developer.
     * 
     */
    @Test
    public void TasksItemJsonControllerIT.testMethodExample() {
        // Setup
        // Previous tasks
        
        // Exercise
        // Execute method to test
        
        // Verify
        // Check results with assertions
    }
    
}
