// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jossemargt.cmsgalatea.model;

import com.jossemargt.cmsgalatea.model.ContestByName;
import io.springlets.format.EntityFormat;

privileged aspect ContestByName_Roo_DTO {
    
    declare @type: ContestByName: @EntityFormat;
    
}
