// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jossemargt.cmsgalatea.repository;

import com.jossemargt.cmsgalatea.repository.ContestRepository;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ContestRepository_Roo_Jpa_Repository {
    
    declare @type: ContestRepository: @Transactional(readOnly = true);
    
}
